version: '3.8'

services:
  app:
    build: .
    container_name: scooter-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # Ma'lumotlar bazasi ulanishi
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scooter_backend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1984
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # Redis ulanishi
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      # Xavfsizlik kalitlari (JWT)
      JWT_SECRET: veryveryveryveryveryverysecuresecretkey123456
      JWT_EXPIRATION: 86400000

     

      # 🔒 SERVER UCHUN PRODUCTION SOZLAMALARI (Properties faylni o'zgartirmasdan shu yerda sozlaymiz)
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO

    networks:
      - scooter-network

  db:
    image: postgres:15
    container_name: scooter-db
    restart: always
    environment:
      POSTGRES_DB: scooter_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1984
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scooter_backend"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - scooter-network

  redis:
    image: redis:7
    container_name: scooter-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scooter-network

volumes:
  postgres_data:
  redis_data:

networks:
  scooter-network: