server.port=8080
spring.application.name=scooter-backend

# Standart sozlamalar (Docker Compose bularni o'zi yuqoridagi qiymatlar bilan almashtiradi)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.default_schema=public

spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:DEBUG}

# Tashqaridan keladigan o'zgaruvchilar
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini