server.port=8080

spring.application.name=scooter-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/scooter_backend
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379

spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=my-secret-key-123456
jwt.expiration=86400000

yandex.api.key=your-real-api-key