server.port=8080

spring.application.name=scooter-backend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.expiration=86400000

yandex.api.key=your-real-api-key

jwt.secret=veryveryveryveryveryverysecuresecretkey123456

spring.redis.host=${SPRING_REDIS_HOST}
spring.redis.port=${SPRING_REDIS_PORT}
spring.redis.password=${SPRING_REDIS_PASSWORD}